### ISSUE TITLE
Slow performance sending in #matrix:matrix.org

### ISSUE THREAD

**Issue by ara4n** [ulyssa/iamb#199]
To repro:
 * join #matrix:matrix.org
 * send a message
 * on hitting enter; iamb freezes for about 10s
 * eventually the local-italic echo appears, and then resolves to remote echo.

I mistook this earlier as a lack of local echo (or lack of message queuing / retry semantics), but the actual thing which was tripping me up looks to be freeze on hitting enter.

**Comment by grzegorz-aleksander-klementowski** [comment]
Not sure, if it is related to it, but I think so.. I found out that thte app eating a lot of CPU resources, even when any chat is off. It is taking around 45%-60%.
![Przechwycenie obrazu ekranu_2024-01-30_19-06-55](https://github.com/ulyssa/iamb/assets/125459323/6676f636-b998-426f-9c43-d5ba75de20e3)

**Comment by paulcarroty** [comment]
The CPU usage is fixed: https://github.com/ulyssa/iamb/pull/168

**Comment by ara4n** [comment]
I was also suffering the CPU problem, which now appear to be fixed - however, it's still freezing for 10s on trying to send a msg in Matrix HQ (this on 0.0.9).

**Comment by roland-5** [comment]
> I was also suffering the CPU problem, which now appears to be fixed - however, it's still freezing for 10s on trying to send a msg in Matrix HQ (this on 0.0.9).

I can confirm this. In rooms with many people and messages, if I send a message there is delay (about 10 seconds). This isn't a case if I talk in direct messages 1:1.

**Comment by ulyssa** [comment]
This should be resolved by #627.
